// <auto-generated />
using FccDesktopAgent.Core.Buffer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FccDesktopAgent.Core.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    partial class AgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("FccDesktopAgent.Core.Buffer.Entities.AgentConfigRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agent_config", (string)null);
                });

            modelBuilder.Entity("FccDesktopAgent.Core.Buffer.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_al_time");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("FccDesktopAgent.Core.Buffer.Entities.BufferedTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttendantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("FccTransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FccVendor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalReceiptNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IngestionSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUploadAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUploadError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("NozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitPriceMinorPerLitre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VolumeMicrolitres")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FccTransactionId", "SiteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_bt_dedup");

                    b.HasIndex("SyncStatus", "CreatedAt")
                        .HasDatabaseName("ix_bt_sync_status");

                    b.HasIndex("SyncStatus", "UpdatedAt")
                        .HasDatabaseName("ix_bt_cleanup");

                    b.HasIndex("SyncStatus", "PumpNumber", "CompletedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_bt_local_api");

                    b.ToTable("buffered_transactions", (string)null);
                });

            modelBuilder.Entity("FccDesktopAgent.Core.Buffer.Entities.NozzleMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FccNozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FccPumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OdooNozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OdooPumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode", "FccPumpNumber", "FccNozzleNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_nozzles_fcc_lookup");

                    b.HasIndex("SiteCode", "OdooPumpNumber", "OdooNozzleNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_nozzles_odoo_lookup");

                    b.ToTable("nozzles", (string)null);
                });

            modelBuilder.Entity("FccDesktopAgent.Core.Buffer.Entities.PreAuthRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActualVolume")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AmountVariance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttendantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerBusinessName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerTaxId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DispensingAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FccAuthorizationCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FccCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCloudSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedFccTransactionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("NozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OdooOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RequestedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VarianceBps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsCloudSynced", "CreatedAt")
                        .HasDatabaseName("ix_par_unsent");

                    b.HasIndex("OdooOrderId", "SiteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_par_idemp");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_par_expiry");

                    b.ToTable("pre_auth_records", (string)null);
                });

            modelBuilder.Entity("FccDesktopAgent.Core.Buffer.Entities.SyncStateRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConfigSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFccSequence")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatusSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUploadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sync_state", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
