// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualLab.Infrastructure.Persistence;

#nullable disable

namespace VirtualLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VirtualLabDbContext))]
    partial class VirtualLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("VirtualLab.Domain.Models.CallbackAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CallbackTargetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsePayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SimulatedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CallbackTargetId", "AttemptedAtUtc");

                    b.HasIndex("SimulatedTransactionId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("CallbackAttempts", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.CallbackTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHeaderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasicAuthPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicAuthUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabEnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabEnvironmentId");

                    b.HasIndex("TargetKey")
                        .IsUnique();

                    b.HasIndex("SiteId", "IsActive");

                    b.ToTable("CallbackTargets", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.FccSimulatorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndpointBasePath")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointSurfaceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureSimulationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldMappingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabEnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreAuthMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestTemplatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseTemplatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorFamily")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabEnvironmentId", "ProfileKey")
                        .IsUnique();

                    b.HasIndex("LabEnvironmentId", "AuthMode", "DeliveryMode", "PreAuthMode");

                    b.ToTable("FccSimulatorProfiles", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.LabEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeterministicSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeededAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("LabEnvironments", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.LabEventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FccSimulatorProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreAuthSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScenarioRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SimulatedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FccSimulatorProfileId");

                    b.HasIndex("PreAuthSessionId");

                    b.HasIndex("ScenarioRunId");

                    b.HasIndex("SimulatedTransactionId");

                    b.HasIndex("Category", "OccurredAtUtc");

                    b.HasIndex("CorrelationId", "OccurredAtUtc");

                    b.HasIndex("SiteId", "Category", "OccurredAtUtc");

                    b.ToTable("LabEventLogs", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Nozzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FccNozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("NozzleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PumpId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimulationStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "State");

                    b.HasIndex("PumpId", "NozzleNumber")
                        .IsUnique();

                    b.ToTable("Nozzles", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.PreAuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AuthorizedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalRequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FinalVolume")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NozzleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PumpId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawRequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReservedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScenarioRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimelineJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("NozzleId");

                    b.HasIndex("PumpId");

                    b.HasIndex("ScenarioRunId");

                    b.HasIndex("SiteId", "CreatedAtUtc");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("PreAuthSessions", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabEnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabEnvironmentId", "ProductCode")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Pump", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FccPumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("LayoutX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayoutY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "FccPumpNumber");

                    b.HasIndex("SiteId", "PumpNumber")
                        .IsUnique();

                    b.ToTable("Pumps", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.ScenarioDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeterministicSeed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabEnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplaySignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabEnvironmentId", "ScenarioKey")
                        .IsUnique();

                    b.ToTable("ScenarioDefinitions", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.ScenarioRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplaySeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplaySignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScenarioDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReplaySignature");

                    b.HasIndex("ScenarioDefinitionId");

                    b.HasIndex("SiteId", "StartedAtUtc");

                    b.ToTable("ScenarioRuns", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.SimulatedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryCursor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NozzleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreAuthSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PumpId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawHeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScenarioRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimelineJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ExternalTransactionId");

                    b.HasIndex("NozzleId");

                    b.HasIndex("PreAuthSessionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PumpId");

                    b.HasIndex("ScenarioRunId");

                    b.HasIndex("SiteId", "OccurredAtUtc");

                    b.HasIndex("SiteId", "Status", "OccurredAtUtc");

                    b.ToTable("SimulatedTransactions", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActiveFccSimulatorProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHeaderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicAuthPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicAuthUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("InboundAuthMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LabEnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreAuthMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveFccSimulatorProfileId");

                    b.HasIndex("SiteCode")
                        .IsUnique();

                    b.HasIndex("LabEnvironmentId", "ActiveFccSimulatorProfileId");

                    b.HasIndex("SiteCode", "IsActive");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.CallbackAttempt", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.CallbackTarget", "CallbackTarget")
                        .WithMany("CallbackAttempts")
                        .HasForeignKey("CallbackTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.SimulatedTransaction", "SimulatedTransaction")
                        .WithMany("CallbackAttempts")
                        .HasForeignKey("SimulatedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallbackTarget");

                    b.Navigation("SimulatedTransaction");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.CallbackTarget", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.LabEnvironment", "LabEnvironment")
                        .WithMany("CallbackTargets")
                        .HasForeignKey("LabEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.Site", "Site")
                        .WithMany("CallbackTargets")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LabEnvironment");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.FccSimulatorProfile", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.LabEnvironment", "LabEnvironment")
                        .WithMany("Profiles")
                        .HasForeignKey("LabEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabEnvironment");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.LabEventLog", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.FccSimulatorProfile", "FccSimulatorProfile")
                        .WithMany()
                        .HasForeignKey("FccSimulatorProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualLab.Domain.Models.PreAuthSession", "PreAuthSession")
                        .WithMany()
                        .HasForeignKey("PreAuthSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualLab.Domain.Models.ScenarioRun", "ScenarioRun")
                        .WithMany("EventLogs")
                        .HasForeignKey("ScenarioRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualLab.Domain.Models.SimulatedTransaction", "SimulatedTransaction")
                        .WithMany()
                        .HasForeignKey("SimulatedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualLab.Domain.Models.Site", "Site")
                        .WithMany("EventLogs")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FccSimulatorProfile");

                    b.Navigation("PreAuthSession");

                    b.Navigation("ScenarioRun");

                    b.Navigation("SimulatedTransaction");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Nozzle", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.Product", "Product")
                        .WithMany("Nozzles")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.Pump", "Pump")
                        .WithMany("Nozzles")
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Pump");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.PreAuthSession", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VirtualLab.Domain.Models.Pump", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VirtualLab.Domain.Models.ScenarioRun", "ScenarioRun")
                        .WithMany("PreAuthSessions")
                        .HasForeignKey("ScenarioRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualLab.Domain.Models.Site", "Site")
                        .WithMany("PreAuthSessions")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");

                    b.Navigation("Pump");

                    b.Navigation("ScenarioRun");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Product", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.LabEnvironment", "LabEnvironment")
                        .WithMany("Products")
                        .HasForeignKey("LabEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabEnvironment");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Pump", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.Site", "Site")
                        .WithMany("Pumps")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.ScenarioDefinition", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.LabEnvironment", "LabEnvironment")
                        .WithMany("ScenarioDefinitions")
                        .HasForeignKey("LabEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabEnvironment");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.ScenarioRun", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.ScenarioDefinition", "ScenarioDefinition")
                        .WithMany("Runs")
                        .HasForeignKey("ScenarioDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.Site", "Site")
                        .WithMany("ScenarioRuns")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScenarioDefinition");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.SimulatedTransaction", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.PreAuthSession", "PreAuthSession")
                        .WithMany("Transactions")
                        .HasForeignKey("PreAuthSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualLab.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.Pump", "Pump")
                        .WithMany()
                        .HasForeignKey("PumpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.ScenarioRun", "ScenarioRun")
                        .WithMany("Transactions")
                        .HasForeignKey("ScenarioRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualLab.Domain.Models.Site", "Site")
                        .WithMany("Transactions")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");

                    b.Navigation("PreAuthSession");

                    b.Navigation("Product");

                    b.Navigation("Pump");

                    b.Navigation("ScenarioRun");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Site", b =>
                {
                    b.HasOne("VirtualLab.Domain.Models.FccSimulatorProfile", "ActiveFccSimulatorProfile")
                        .WithMany("Sites")
                        .HasForeignKey("ActiveFccSimulatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirtualLab.Domain.Models.LabEnvironment", "LabEnvironment")
                        .WithMany("Sites")
                        .HasForeignKey("LabEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveFccSimulatorProfile");

                    b.Navigation("LabEnvironment");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.CallbackTarget", b =>
                {
                    b.Navigation("CallbackAttempts");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.FccSimulatorProfile", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.LabEnvironment", b =>
                {
                    b.Navigation("CallbackTargets");

                    b.Navigation("Products");

                    b.Navigation("Profiles");

                    b.Navigation("ScenarioDefinitions");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.PreAuthSession", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Product", b =>
                {
                    b.Navigation("Nozzles");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Pump", b =>
                {
                    b.Navigation("Nozzles");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.ScenarioDefinition", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.ScenarioRun", b =>
                {
                    b.Navigation("EventLogs");

                    b.Navigation("PreAuthSessions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.SimulatedTransaction", b =>
                {
                    b.Navigation("CallbackAttempts");
                });

            modelBuilder.Entity("VirtualLab.Domain.Models.Site", b =>
                {
                    b.Navigation("CallbackTargets");

                    b.Navigation("EventLogs");

                    b.Navigation("PreAuthSessions");

                    b.Navigation("Pumps");

                    b.Navigation("ScenarioRuns");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
