using FccDesktopAgent.Core.Adapter.Common;
using FccDesktopAgent.Core.Security;

namespace FccDesktopAgent.Core.Buffer.Entities;

/// <summary>
/// EF entity for pre-authorization lifecycle tracking in the local SQLite buffer.
/// Active idempotency key: (OdooOrderId, SiteCode) for non-terminal records only.
/// </summary>
public sealed class PreAuthRecord
{
    /// <summary>UUID v4 generated by the agent. Primary key.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();

    public string SiteCode { get; set; } = string.Empty;

    /// <summary>Odoo order ID from the POS request. Part of idempotency key.</summary>
    public string OdooOrderId { get; set; } = string.Empty;

    /// <summary>Odoo pump number (translated to FCC number via NozzleMapping before sending to FCC).</summary>
    public int PumpNumber { get; set; }

    /// <summary>Odoo nozzle number (translated to FCC nozzle number via NozzleMapping).</summary>
    public int NozzleNumber { get; set; }

    public string ProductCode { get; set; } = string.Empty;

    /// <summary>Requested authorization amount in minor currency units.</summary>
    public long RequestedAmount { get; set; }

    /// <summary>Unit price in minor units per litre at time of pre-auth.</summary>
    public long UnitPrice { get; set; }

    public string Currency { get; set; } = string.Empty;

    public PreAuthStatus Status { get; set; } = PreAuthStatus.Pending;

    /// <summary>Whether this record has been forwarded to cloud.</summary>
    public bool IsCloudSynced { get; set; }

    public string? VehicleNumber { get; set; }

    [SensitiveData] public string? CustomerName { get; set; }
    [SensitiveData] public string? CustomerTaxId { get; set; }

    public string? CustomerBusinessName { get; set; }
    public string? AttendantId { get; set; }

    /// <summary>Structured failure/cancellation reason code (e.g. "FCC_DECLINED", "FCC_TIMEOUT").</summary>
    public string? FailureReason { get; set; }

    /// <summary>Primary FCC match key returned by FCC on authorization.</summary>
    public string? FccCorrelationId { get; set; }
    public string? FccAuthorizationCode { get; set; }
    public string? MatchedFccTransactionId { get; set; }

    public long? ActualAmount { get; set; }
    public long? ActualVolume { get; set; }
    public long? AmountVariance { get; set; }
    public int? VarianceBps { get; set; }

    public DateTimeOffset RequestedAt { get; set; }
    public DateTimeOffset ExpiresAt { get; set; }

    public DateTimeOffset? AuthorizedAt { get; set; }
    public DateTimeOffset? DispensingAt { get; set; }
    public DateTimeOffset? CompletedAt { get; set; }
    public DateTimeOffset? CancelledAt { get; set; }
    public DateTimeOffset? ExpiredAt { get; set; }
    public DateTimeOffset? FailedAt { get; set; }

    public string SchemaVersion { get; set; } = "1.0";

    // ── Replication (Multi-Agent HA) ──────────────────────────────────────

    /// <summary>Monotonic replication sequence assigned by the primary. Default 0 (unassigned).</summary>
    public long ReplicationSeq { get; set; }

    /// <summary>Agent ID that originally created this record. Null for pre-replication records.</summary>
    public string? SourceAgentId { get; set; }

    /// <summary>When this record was replicated from the primary. Null for locally-created records.</summary>
    public DateTimeOffset? ReplicatedAt { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;
}
