using FccDesktopAgent.Core.Adapter.Common;

namespace FccDesktopAgent.Core.Buffer.Entities;

/// <summary>
/// A fuel dispensing transaction polled from the FCC and buffered locally.
/// PumpNumber/NozzleNumber are FCC numbers as received from the FCC (not Odoo numbers).
/// Uploaded to cloud in CreatedAt ASC order. Upload failures are retried.
/// </summary>
public sealed class BufferedTransaction
{
    /// <summary>UUID v4 generated by the agent. Primary key.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>Opaque transaction ID from the FCC. Used with SiteCode for deduplication.</summary>
    public string FccTransactionId { get; set; } = string.Empty;

    public string SiteCode { get; set; } = string.Empty;

    /// <summary>FCC pump number (not Odoo pump number).</summary>
    public int PumpNumber { get; set; }

    /// <summary>FCC nozzle number (not Odoo nozzle number).</summary>
    public int NozzleNumber { get; set; }

    public string ProductCode { get; set; } = string.Empty;

    /// <summary>Volume dispensed in microlitres. NEVER floating point.</summary>
    public long VolumeMicrolitres { get; set; }

    /// <summary>Amount dispensed in minor currency units (e.g. cents). NEVER floating point.</summary>
    public long AmountMinorUnits { get; set; }

    /// <summary>Unit price in minor units per litre. NEVER floating point.</summary>
    public long UnitPriceMinorPerLitre { get; set; }

    public string CurrencyCode { get; set; } = string.Empty;

    public DateTimeOffset StartedAt { get; set; }
    public DateTimeOffset CompletedAt { get; set; }

    public string? FiscalReceiptNumber { get; set; }

    public string FccVendor { get; set; } = string.Empty;

    public string? AttendantId { get; set; }

    /// <summary>Canonical transaction lifecycle status.</summary>
    public TransactionStatus Status { get; set; } = TransactionStatus.Pending;

    /// <summary>Edge-side upload tracking state.</summary>
    public SyncStatus SyncStatus { get; set; } = SyncStatus.Pending;

    public string IngestionSource { get; set; } = string.Empty;

    /// <summary>Raw FCC payload preserved for auditing and replay.</summary>
    public string RawPayloadJson { get; set; } = string.Empty;

    public string? CorrelationId { get; set; }

    public int UploadAttempts { get; set; }
    public DateTimeOffset? LastUploadAttemptAt { get; set; }
    public string? LastUploadError { get; set; }

    public string SchemaVersion { get; set; } = "1.0";

    // ── WebSocket backward-compat fields (Odoo POS cart workflow) ──────────

    /// <summary>Odoo order UUID set via WebSocket manager_update / attendant_update.</summary>
    public string? OrderUuid { get; set; }

    /// <summary>Odoo order ID stamped by acknowledge. Null until acknowledged.</summary>
    public string? OdooOrderId { get; set; }

    /// <summary>Whether Odoo has added this transaction to the POS cart.</summary>
    public bool AddToCart { get; set; }

    /// <summary>Odoo payment ID set via WebSocket.</summary>
    public string? PaymentId { get; set; }

    /// <summary>Whether this transaction was manually discarded via WebSocket.</summary>
    public bool IsDiscard { get; set; }

    /// <summary>Timestamp when Odoo acknowledged this transaction. Null until acknowledged.</summary>
    public DateTimeOffset? AcknowledgedAt { get; set; }

    // ── Fiscalization retry tracking (GAP-7) ──────────────────────────────

    /// <summary>Number of fiscalization attempts made.</summary>
    public int FiscalAttempts { get; set; }

    /// <summary>ISO 8601 UTC of last fiscalization attempt.</summary>
    public DateTimeOffset? LastFiscalAttemptAt { get; set; }

    /// <summary>NONE | PENDING | SUCCESS | DEAD_LETTER</summary>
    public string FiscalStatus { get; set; } = "NONE";

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;
}
