namespace FccMiddleware.Contracts.Ingestion;

/// <summary>
/// Request body for POST /api/v1/transactions/upload.
/// An Edge Agent submits a batch of pre-normalized canonical transactions buffered locally.
/// Maximum 500 records per batch.
/// </summary>
public sealed record UploadRequest
{
    /// <summary>Batch of pre-normalized transactions to upload. Maximum 500 items.</summary>
    public required IReadOnlyList<UploadTransactionRecord> Transactions { get; init; }

    /// <summary>
    /// Optional batch-level idempotency key generated by the Edge Agent per upload attempt.
    /// When present, cloud caches the batch result and returns it instantly on retry.
    /// </summary>
    public string? UploadBatchId { get; init; }
}
