using Amazon.SimpleEmailV2;
using Amazon.SimpleEmailV2.Model;
using FccMiddleware.Application.Notifications;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace FccMiddleware.Infrastructure.Messaging;

public sealed class AwsSesEmailService : IEmailNotificationService
{
    private readonly EmailNotificationOptions _options;
    private readonly ILogger<AwsSesEmailService> _logger;
    private readonly IAmazonSimpleEmailServiceV2 _ses;

    public AwsSesEmailService(
        IAmazonSimpleEmailServiceV2 ses,
        IOptions<EmailNotificationOptions> options,
        ILogger<AwsSesEmailService> logger)
    {
        _ses = ses;
        _options = options.Value;
        _logger = logger;
    }

    public async Task SendBootstrapTokenGeneratedAsync(
        BootstrapTokenGeneratedEmail email, CancellationToken cancellationToken)
    {
        if (_options.AdminRecipients.Length == 0)
        {
            _logger.LogWarning("No admin recipients configured for email notifications");
            return;
        }

        var subject = $"Bootstrap Token Generated — Site {email.SiteCode}";
        var body = BuildHtmlBody(email);

        var request = new SendEmailRequest
        {
            FromEmailAddress = _options.FromAddress,
            Destination = new Destination
            {
                ToAddresses = _options.AdminRecipients.ToList()
            },
            Content = new EmailContent
            {
                Simple = new Message
                {
                    Subject = new Content { Data = subject },
                    Body = new Body
                    {
                        Html = new Content { Data = body }
                    }
                }
            }
        };

        await _ses.SendEmailAsync(request, cancellationToken);

        _logger.LogInformation(
            "Bootstrap token notification email sent for site {SiteCode}, token {TokenId} to {RecipientCount} recipient(s)",
            email.SiteCode, email.TokenId, _options.AdminRecipients.Length);
    }

    private static string BuildHtmlBody(BootstrapTokenGeneratedEmail email) =>
        $"""
        <html>
        <body style="font-family: sans-serif; color: #1e293b; max-width: 600px;">
            <h2 style="color: #0f172a;">Bootstrap Token Generated</h2>
            <table style="border-collapse: collapse; width: 100%;">
                <tr>
                    <td style="padding: 8px 12px; font-weight: 600; color: #64748b; border-bottom: 1px solid #e2e8f0;">Site Code</td>
                    <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">{email.SiteCode}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 12px; font-weight: 600; color: #64748b; border-bottom: 1px solid #e2e8f0;">Token ID</td>
                    <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;"><code>{email.TokenId}</code></td>
                </tr>
                <tr>
                    <td style="padding: 8px 12px; font-weight: 600; color: #64748b; border-bottom: 1px solid #e2e8f0;">Generated By</td>
                    <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">{email.GeneratedBy}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 12px; font-weight: 600; color: #64748b; border-bottom: 1px solid #e2e8f0;">Expires At</td>
                    <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">{email.ExpiresAt:yyyy-MM-dd HH:mm:ss} UTC</td>
                </tr>
            </table>
            <p style="margin-top: 16px; padding: 12px; background: #fefce8; border: 1px solid #fde047; border-radius: 4px; font-size: 0.9rem;">
                The raw token is not included in this email for security reasons.
                View it in the portal immediately after generation.
            </p>
            <p style="margin-top: 16px; font-size: 0.8rem; color: #94a3b8;">
                This is an automated notification from FCC Middleware.
            </p>
        </body>
        </html>
        """;
}
