using FccMiddleware.Domain.Enums;
using FccMiddleware.Domain.Interfaces;

namespace FccMiddleware.Domain.Entities;

/// <summary>
/// Single-use provisioning token for Edge Agent device registration.
/// Generated by portal/admin API, delivered via QR code, consumed during registration.
/// The raw token is never stored — only its SHA-256 hex hash.
/// </summary>
public class BootstrapToken : ITenantScoped
{
    public Guid Id { get; set; }
    public Guid LegalEntityId { get; set; }
    public string SiteCode { get; set; } = null!;

    /// <summary>SHA-256 hex (lowercase) of the raw bootstrap token. Looked up during registration.</summary>
    public string TokenHash { get; set; } = null!;

    public ProvisioningTokenStatus Status { get; set; } = ProvisioningTokenStatus.ACTIVE;
    public string CreatedBy { get; set; } = null!;
    public string? CreatedByActorId { get; set; }
    public string? CreatedByActorDisplay { get; set; }
    public DateTimeOffset ExpiresAt { get; set; }
    public DateTimeOffset? UsedAt { get; set; }
    public DateTimeOffset? RevokedAt { get; set; }
    public string? RevokedByActorId { get; set; }
    public string? RevokedByActorDisplay { get; set; }

    /// <summary>The device that consumed this token. Set on successful registration.</summary>
    public Guid? UsedByDeviceId { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Cloud environment key (e.g. "PRODUCTION", "STAGING"). Null for legacy tokens.</summary>
    public string? Environment { get; set; }

    // Navigation
    public LegalEntity LegalEntity { get; set; } = null!;

    /// <summary>
    /// Returns true if this token can be used for registration right now.
    /// </summary>
    public bool IsUsable(DateTimeOffset asOf) =>
        Status == ProvisioningTokenStatus.ACTIVE
        && UsedAt is null
        && ExpiresAt > asOf;
}
